services:
  chat-websocket-backend:
    container_name: chat-websocket-backend
    build: ./backend/.
    ports:
      - "19090:9090"
    networks:
      - chatwebsocket_network
    restart: unless-stopped

  chat-websocket-frontend:
    container_name: chat-websocket-frontend
    build: ./frontend/.
    ports:
      - "19000:3000"
    environment:
      - NEXT_PUBLIC_WS_URL=ws://localhost:19090/ws
    depends_on:
      - chat-websocket-backend
    networks:
      - chatwebsocket_network
    restart: unless-stopped
  

  db_chat:
    image: postgres:12 
    container_name: db-chatwebsocket
    restart: always
    environment:
      POSTGRES_DB: chatdb
      POSTGRES_USER: chathadmin
      POSTGRES_PASSWORD: 1239012
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chatwebsocket_network

volumes:
  pgdata:



networks:
  chatwebsocket_network:
    driver: bridge