version: "3.9"

services:
  chat-websocket-backend:
    container_name: chat-websocket-backend
    build: ./backend/.
    ports:
      - "19090:9090"
    env_file:
      - ./backend/.env
    depends_on:
      - db_chat
    networks:
      - chatwebsocket_network
    restart: unless-stopped

  chat-websocket-frontend:
    container_name: chat-websocket-frontend
    build: ./frontend/.
    ports:
      - "19000:3000"
    environment:
      - NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL}
    depends_on:
      - chat-websocket-backend
    networks:
      - chatwebsocket_network
    restart: unless-stopped

  db_chat:
    image: postgres:12
    container_name: db-chatwebsocket
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - chatwebsocket_network

volumes:
  pgdata:

networks:
  chatwebsocket_network:
    driver: bridge
